# Generated by Django 4.0.3 on 2022-05-29 05:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=80)),
                ('subject', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=60)),
                ('contact_no', models.CharField(max_length=10)),
                ('pan_no', models.CharField(max_length=10)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('residential_address', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=60)),
                ('official_address', models.CharField(max_length=200)),
                ('income', models.CharField(max_length=30)),
                ('existing_loan', models.CharField(max_length=10)),
                ('expected_loan_amount', models.FloatField()),
                ('expected_loan_tenure', models.CharField(max_length=30)),
                ('collateral_name', models.CharField(blank=True, max_length=200, null=True)),
                ('collateral_value', models.FloatField()),
                ('profile_photo', models.FileField(upload_to='')),
                ('pan_image', models.FileField(upload_to='')),
                ('aadhar_image', models.FileField(upload_to='')),
                ('account_number', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('bank_ifsc_code', models.CharField(max_length=30)),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('reject_reason', models.CharField(blank=True, max_length=1000, null=True)),
                ('loan_application_status', models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('rejected_date', models.DateTimeField(blank=True, null=True)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('disbursed_date', models.DateTimeField(blank=True, null=True)),
                ('first_payment_date', models.DateField(blank=True, null=True)),
                ('tenure_left', models.IntegerField(blank=True, null=True)),
                ('payment_schedule', models.FileField(blank=True, null=True, upload_to='')),
                ('loan_completed', models.BooleanField(default=False)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LoanType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loan_name', models.CharField(max_length=200)),
                ('loan_desc', models.TextField(max_length=1000)),
                ('max_loan_amount', models.FloatField()),
                ('loan_roi', models.FloatField()),
                ('max_loan_duration', models.CharField(max_length=4)),
                ('loan_category', models.CharField(choices=[('Secured', 'Secured'), ('Unsecured', 'Unsecured')], max_length=100)),
                ('need_security', models.BooleanField(blank=True, default=False, null=True)),
                ('loan_image', models.FileField(upload_to='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact', models.CharField(max_length=10)),
                ('full_name', models.CharField(max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('monthly_amount', models.FloatField(blank=True, null=True)),
                ('emi_paid', models.BooleanField(default=False)),
                ('emi_paid_date', models.DateField(blank=True, null=True)),
                ('razorpay_payment_id', models.CharField(blank=True, max_length=200, null=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_schedule', to='loan_app.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LoanDefaultersReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Reminder', 'Reminder'), ('Recovery', 'Recovery')], max_length=100, null=True)),
                ('recovered_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('recovery_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_defaulters', to='loan_app.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='loan_applied_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_type', to='loan_app.loantype'),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
