# Generated by Django 4.0.3 on 2022-04-03 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0007_remove_loantype_loan_image_loantype_loan_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='loan_category',
            field=models.CharField(choices=[('Secured', 'Secured'), ('Unsecured', 'Unsecured')], max_length=100),
        ),
        migrations.DeleteModel(
            name='LoanCategory',
        ),
    ]
