# Generated by Django 4.0.3 on 2022-04-04 09:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_app', '0008_alter_loantype_loan_category_delete_loancategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='LoanApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('application_id', models.CharField(blank=True, max_length=100, null=True)),
                ('full_name', models.CharField(max_length=60)),
                ('contact_no', models.CharField(max_length=10)),
                ('pan_no', models.CharField(max_length=10)),
                ('aadhar_no', models.CharField(max_length=12)),
                ('residential_address', models.CharField(max_length=200)),
                ('service_type', models.CharField(max_length=60)),
                ('official_address', models.CharField(max_length=200)),
                ('income', models.CharField(max_length=30)),
                ('existing_loan', models.CharField(max_length=10)),
                ('expected_loan_amount', models.FloatField()),
                ('expected_loan_tenure', models.CharField(max_length=30)),
                ('profile_photo', models.FileField(upload_to='documents/')),
                ('pan_image', models.FileField(upload_to='documents/')),
                ('aadhar_image', models.FileField(upload_to='documents/')),
                ('remarks', models.CharField(blank=True, max_length=300, null=True)),
                ('loan_application_status', models.CharField(blank=True, default='Pending', max_length=50, null=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('approved_date', models.DateTimeField(blank=True, null=True)),
                ('is_disbursed', models.BooleanField(default=False)),
                ('disbursed_date', models.DateTimeField(blank=True, null=True)),
                ('next_payment_date', models.DateField(blank=True, null=True)),
                ('tenure_left', models.IntegerField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('loan_applied_for', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loan_app.loantype')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
