# Generated by Django 4.0.3 on 2022-04-04 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0010_loantype_need_security_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loantype',
            name='need_security',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
