# Generated by Django 4.0.3 on 2022-04-04 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0011_alter_loantype_need_security'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='collateral_name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='collateral_value',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
