# Generated by Django 4.0.3 on 2022-04-05 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0012_loanapplication_collateral_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='account_number',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_ifsc_code',
            field=models.CharField(default='1', max_length=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='loanapplication',
            name='bank_name',
            field=models.CharField(default='1', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_application_status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Disbursed', 'Disbursed'), ('Rejected', 'Rejected')], default='Pending', max_length=50, null=True),
        ),
    ]
