# Generated by Django 4.0.3 on 2022-04-07 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0013_loanapplication_account_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='rejected_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
