# Generated by Django 4.0.3 on 2022-05-07 06:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0015_loanapplication_payment_schedule'),
    ]

    operations = [
        migrations.AddField(
            model_name='loantype',
            name='loan_image',
            field=models.FileField(default='NONE', upload_to=''),
            preserve_default=False,
        ),
    ]
