# Generated by Django 4.0.3 on 2022-05-07 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0016_loantype_loan_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='reject_reason',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
