# Generated by Django 4.0.3 on 2022-05-08 12:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_app', '0017_loanapplication_reject_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanapplication',
            name='loan_applied_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_type', to='loan_app.loantype'),
        ),
        migrations.CreateModel(
            name='LoanSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_schedule', to='loan_app.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
