# Generated by Django 4.0.3 on 2022-05-08 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0018_alter_loanapplication_loan_applied_for_loanschedule'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loanapplication',
            old_name='next_payment_date',
            new_name='first_payment_date',
        ),
    ]
