# Generated by Django 4.0.3 on 2022-05-08 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0019_rename_next_payment_date_loanapplication_first_payment_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanschedule',
            name='monthly_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
