# Generated by Django 4.0.3 on 2022-05-08 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0020_loanschedule_monthly_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanschedule',
            name='emi_paid',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='loanschedule',
            name='emi_paid_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
