# Generated by Django 4.0.3 on 2022-05-15 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0021_loanschedule_emi_paid_loanschedule_emi_paid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanschedule',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanschedule',
            name='razorpay_payment_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='loanschedule',
            name='razorpay_signature',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
