# Generated by Django 4.0.3 on 2022-05-15 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0022_loanschedule_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loanschedule',
            name='razorpay_order_id',
        ),
        migrations.RemoveField(
            model_name='loanschedule',
            name='razorpay_signature',
        ),
    ]
