# Generated by Django 4.0.3 on 2022-05-21 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('loan_app', '0023_remove_loanschedule_razorpay_order_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='loanapplication',
            name='loan_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='LoanDefaultersReminder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, choices=[('Reminders', 'Reminders'), ('Recovery', 'Recovery')], max_length=100, null=True)),
                ('reminder_count', models.IntegerField(blank=True, default=0, null=True)),
                ('recovered_amount', models.FloatField(blank=True, default=0.0, null=True)),
                ('recovery_date', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('updated_on', models.DateTimeField(auto_now=True)),
                ('loan_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loan_defaulters', to='loan_app.loanapplication')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
