# Generated by Django 4.0.3 on 2022-05-22 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0024_loanapplication_loan_completed_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loandefaultersreminder',
            name='reminder_count',
        ),
        migrations.AlterField(
            model_name='loandefaultersreminder',
            name='status',
            field=models.CharField(blank=True, choices=[('Reminder', 'Reminder'), ('Recovery', 'Recovery')], max_length=100, null=True),
        ),
    ]
