# Generated by Django 4.0.3 on 2022-05-22 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan_app', '0025_remove_loandefaultersreminder_reminder_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loanschedule',
            name='emi_paid',
            field=models.BooleanField(default=False),
        ),
    ]
